services:
  - docker
language: python
env:
    global:
        - QEMU_VER=v2.9.1
    matrix:
        - ARCH=amd64
        - ARCH=armel
        - ARCH=armhf
        - ARCH=aarch64
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # generate dockerfile
  - ./Dockerfile.py --arch=${ARCH} -v --no-build
  # run docker build for first stage to prevent Travis timeout
  - docker build -f Dockerfile_${ARCH} --target build -t pihole:build_${ARCH} .
  - ./Dockerfile.py --arch=${ARCH} -v --no-generate
  - docker images
  # run docker build & tests
  # 2 parallel max b/c race condition with docker fixture (I think?)
  - py.test -vv -n 2 -k "${ARCH}" ./test/
